export interface ExperimentData {
    id_datos: number,
    id_experimento: number,
    masa1: number,
    masa2: number,
    masa3: number,
    masa4: number,
    velocidad1: number,
    velocidad2: number,
    velocidad3: number,
    velocidad4: number,
    velocidad5: number,
    altura1: number,
    altura2: number,
    altura3: number,
    altura4: number,
    tiempo1: Date,
    tiempo2: Date,
    tiempo3: Date,
    tiempo4: Date,
    resultado: null,
    tipoExperimento: string,
    longitud: number,
    gravedad: number,
    angulo_inclinación: number,
    tiempo5: Date
}